### PR TITLE
Remo dev

### PR DESCRIPTION
**Pull request by remo-help**
New changes break something: " unresolved dependency: org.clulab#processors-corenlp_2.12;8.4.2-SNAPSHOT: not found"
@BeckySharp please review and merge once solved

### CODE REVIEW

**Review by BeckySharp — APPROVED** [review]
looks great, thanks for working on this!

**Comment by BeckySharp** [comment]
@remo-help i'll merge once tests pass

**Comment by BeckySharp** [comment]
@adarshp @jastier I think this is the merge that remo wanted you to wait for -- am I right @remo-help ?

**Comment by remo-help** [comment]
@adarshp @BeckySharp @jastier yep, all good to go

**Comment by adarshp** [comment]
Great, thank you!!

**Pull request merged**
