### PR TITLE
Merging the Hackathon branch into main

### PR DESCRIPTION
**Pull request by remo-help**
This includes a bunch of new extraction rules, plus some housekeeping inside of Odin

### CODE REVIEW

**Review by adarshp — COMMENTED** [review]
Thanks @remo-help !

Looks good to me, just one question though - is this file supposed to be empty?

src/main/resources/org/clulab/asist/grammars/sentiment_triggers.yml

**Comment by remo-help** [comment]
> Thanks @remo-help !
> 
> Looks good to me, just one question though - is this file supposed to be empty?
> 
> src/main/resources/org/clulab/asist/grammars/sentiment_triggers.yml

Yes, I created it as a placeholder file for splitting up our triggers into themed files for housekeeping purposes (the trigger file is getting bigger and bigger), but I havent had the chance to properly implement this change, so this file is sort of a "placeholder for changes to come". But we can delete it if we dont want an empty file in main

**Comment by adarshp** [comment]
@remo-help No worries, it's fine to have the placeholder - I was just making sure that it wasn't a file added by mistake. Can you add a comment in the file that explains that it's a placeholder?

Additionally, it looks like there are some failing tests (https://github.com/clulab/tomcat-text/pull/72/checks?check_run_id=2328861453) - can you fix them (or mark them as to be ignored)?

**Comment by remo-help** [comment]
I'm actually not sure what the tests are we have here or why they fail, @BeckySharp ?

**Comment by BeckySharp** [comment]
I'll check tonight or tomorrow early -- will that work?

**Comment by BeckySharp** [comment]
> I'm actually not sure what the tests are we have here or why they fail, @BeckySharp ?

tests are fixed or removed (we can talk more about why I removed the ones I did), they all pass locally.
so, @adarshp assuming travis agrees, we should be able to merge

**Comment by BeckySharp** [comment]
@jastier @adarshp can someone trigger the testing again? seems like a connectivity issue, and tests pass for me

**Comment by adarshp** [comment]
@BeckySharp I retriggered the tests. If the connectivity issue reappears I'm fine with just merging it anyway.

**Review by adarshp — APPROVED** [review]

**Comment by kwalcock** [comment]
We had some other tests fail last night for similar reasons.  They seemed to be working again this morning.

**Comment by adarshp** [comment]
@kwalcock Thanks for letting us know - presumably it's not an issue with Github Actions then (I assume your tests were running on a locally hosted Jenkins instance, right?)

**Comment by kwalcock** [comment]
Yes, these were running on a local install of Jenkins.

**Pull request merged**
