### PR TITLE
master rule file selectable from the command line

### PR DESCRIPTION
**Pull request by jastier**
- The file for the Dialog Agent Rule Engine can be set with with the "--rulepath" command line argument.  
- The rule path is in the same format as in the config file, e.g. "/org/clulab/asist/grammars/master.yml"
- If the argument is not set, the file specified in the config file is used.

### CODE REVIEW

**Comment by adarshp** [comment]
@remo-help  - can you test this PR out and see if it works for you?

**Comment by remo-help** [comment]
will do later today

**Comment by jastier** [comment]
Currently, the path is relative - the same as used by the config file.      

I can modify it to take absolute paths.

**Comment by adarshp** [comment]
@jastier - @remo-help  had tried the relative path already but it didn't work. Can you reproduce his error?

**Comment by remo-help** [comment]
perhaps I am using the wrong relative path?
here is what I tried:
`sbt "runMain org.clulab.asist.apps.RunDialogAgent stdin --rulepath src/main/resources/org/clulab/asist/grammars/study2_master.yml"`

**Comment by jastier** [comment]
The config file (./src/main/resources/application.conf) defines the masterRulesPath variable as:

TomcatRuleEngine {
// Override the default values here
      masterRulesPath = "/org/clulab/asist/grammars/master.yml"
...
}

I stayed with this pattern when defining the command line argument.

See if this works:  
sbt "runMain org.clulab.asist.apps.RunDialogAgent stdin --rulepath /org/clulab/asist/grammars/study2_master.yml"

**Comment by remo-help** [comment]
that works, thanks

**Review by remo-help — APPROVED** [review]

**Pull request merged**
