### PR TITLE
Add tests for HelpRequest and ToolBroken labels.

### PR DESCRIPTION
**Pull request by Yuweien**

### CODE REVIEW

**Comment by Yuweien** [comment]
Hi @remo-help , for this time, the sbt test passed locally on my computer but failed on the CI test in Github. I tried to read the error messages and I'm not sure what happened. Could you please take a look at it?

**Comment by remo-help** [comment]
@Yuweien this might be an issue on the github side, @jastier any idea why the CI compilation is failing here?

**Comment by kwalcock** [comment]
The recent networking problems in the CS department seem to have been preventing access to the artifactory server and causing the testing to go awry.  It is supposed to have been fixed in the meantime, so I restarted the tests.  HTH.

**Comment by adarshp** [comment]
Thank you 

> The recent networking problems in the CS department seem to have been preventing access to the artifactory server and causing the testing to go awry. It is supposed to have been fixed in the meantime, so I restarted the tests. HTH.

Thank you @kwalcock !!

**Review by remo-help — APPROVED** [review]
looks good, neat and tidy code too!

**Pull request merged**
