### PR TITLE
Add "could you take care of.." pattern to Instruction, also some small changes that I forgot to merge before

### PR DESCRIPTION
**Pull request by Yuweien**
Hi @remo-help , I wrote a rule for the pattern "Could you please take care of the rubble, blue." under the Instruction rule. It worked in the Odin tutorial playground(screenshot below). But it is not extracted as "Instruction", but as "YesNoQuestions" in our webapp. I'm thinking, is this because the YesNoQuestion has a higher priority than instruction? Could you please take a look at my code? Thank you very much!
image

### CODE REVIEW

**Review by adarshp — CHANGES_REQUESTED** [review]
@Yuweien  - could you please do the following:

1. Resolve the merge conflicts
2. Update the title of the PR to something more descriptive

Thanks!

**Comment by remo-help** [comment]
@Yuweien I can take a look at this later today

**Comment by Yuweien** [comment]
OMG, I seemed messed up with the conflicts which result in failing the CI test. How can I restore the conflicts?

**Comment by adarshp** [comment]
> OMG, I seemed messed up with the conflicts which result in failing the CI test. How can I restore the conflicts?

I've asked @vincentraymond-ua to meet with you to go over how to do this.

**Comment by remo-help** [comment]
@Yuweien are you sure you are calling the webapp from this branch?
I tried checking out your branch and I cant start the webapp, there seem to be some duplicate roomnames

**Comment by remo-help** [comment]
I think you need to checkout a fresh master branch, checkout a new branch from there and add your rule

We moved a lot of files around and I thin you worked on a very old branch, this resulted in some conflicts

**Comment by Yuweien** [comment]
> I think you need to checkout a fresh master branch, checkout a new branch from there and add your rule
> 
> We moved a lot of files around and I thin you worked on a very old branch, this resulted in some conflicts

Ah I see. I think the conflicts are caused by my previous commits. Those are small changes that I made a long time ago and committed but forgot to pull request. I'll try checkout a new branch from the newest master and move the changes there. Thank you!

**Comment by remo-help** [comment]
> > I think you need to checkout a fresh master branch, checkout a new branch from there and add your rule
> > We moved a lot of files around and I thin you worked on a very old branch, this resulted in some conflicts
> 
> Ah I see. I think the conflicts are caused by my previous commits. Those are small changes that I made a long time ago and committed but forgot to pull request. I'll try checkout a new branch from the newest master and move the changes there. Thank you!

let me know when this is done, then I can review the code

**Pull request closed without merging**
